### PR TITLE
Make form fields filterable and align fields with Woocommerce

### PR DESCRIPTION
**Pull request by jupitercow**
I am finding the default fields a bit of a road block. The fields should be filterable, so that developers can choose the precise fields they need from participants. While this version doesn't remove any existing functionality, it creates a much simpler interface for controlling the fields just by filtering a single array.

The new filter is `registrations_participant_fields`.

Example:

```
function custom_registrations_participant_fields( $fields ) {
	foreach ( $fields as $key => $field ) {
		if ( 'name' === $field['name'] ) {
			unset($fields[$key]);
		}
	}

	$fields[] = array(
		'class'         => [ 'participant-address', 'form-row-wide', 'address-field' ],
		'label'         => __( 'Street address', 'patch' ),
		'name'          => 'address_1',
		'placeholder'   => __( 'House number and street name', 'patch'),
		'required'      => true,
		'type'          => 'text',
	);

	return $fields;
}
add_filter( 'registrations_participant_fields', 'custom_registrations_participant_fields' );
```

Currently the plugin also offers "optional", non-required fields that then are required. It is very confusing for end users. This will fix that as well.

Lastly. The field labels were not aligned with Woocommerce. I aligned them to match the program they integrating with: 'First name', 'Last name', 'Email address'. I kept the field keys the same. Personally I found "Name" with a placeholder of "Mary Anna" confusing. I thought that was a full name and then Surname was a Last Name as well. 

Hope this is useful. It would be a huge help for me.

Thanks.
Jake.

### CODE REVIEW

**Comment by jupitercow** [comment]
The array could be further updated to this. The surname should be required, and I think it would be good to use the first/last classes to better establish the first name and last name, and to be more inline with woocommerce default fields.

```
			'participant_fields' => array(
				array(
					'class'         => array( 'participant-name', 'form-row-first' ),
					'label'         => __( 'First name', 'registrations-for-woocommerce' ),
					'name'          => 'name',
					'type'          => 'text',
					'required'      => true,
				),
				array(
					'class'         => array( 'participant-surname', 'form-row-last' ),
					'label'         => __( 'Last name', 'registrations-for-woocommerce' ),
					'name'          => 'surname',
					'type'          => 'text',
					'required'      => true,
				),
				array(
					'class'         => array( 'participant-email', 'form-row-wide' ),
					'label'         => __( 'Email address', 'registrations-for-woocommerce' ),
					'name'          => 'email',
					'type'          => 'text',
					'required'      => true,
				),
			),
```

**Comment by allysonsouza** [comment]
Hi @jupitercow,

Finally I was with some free time to test the pull requests and do some improvements in Registrations for WooCommerce, but how @ajlowndes said, it looks like you removed everything from the project in your first commit. I'm not an expert in Git, but I'm trying to figure out what happened, but if you could take a look at your side would be great too. And thanks for your colaboration!

**Comment by jupitercow** [comment]
That took way too long. I got sidetracked. It appears that the last commit was complete mistake. The previous commit was the correct last one. I reverted the bad commit. This is still a good pull request that would be very useful.

**Comment by allysonsouza** [comment]
Thank you @jupitercow, I'll try to test it this weekend!

**Pull request merged**
