### PR TITLE
Added reports functionality

### LINKED ISSUE #8: Reports functionality
Add reports functionality to list users registered for each event in WooCommerce Reports.

### PR DESCRIPTION
**Pull request by Shirkit**
Actually just fixed for grabbing the correct data in the new format

Should resolve #8

### CODE REVIEW

**Comment by allysonsouza** [comment]
Hi @Shirkit,

Great job! Just two thing I think are little bugs, maybe easy to solve (if I have time I'll gave a look).

1. In the first screen of the reports is showing repeated event dates.
image

2. At the two screens pagination is displayed without necessity.

**Comment by Shirkit** [comment]
Oppps, good thing you tested as well, I'll look into it. My tests didn't reveal that.

**Comment by Shirkit** [comment]
Ok, that should do it.

Just wanted to clarify that the pagination was never implemented. To properly use Pagination while using a WP_List_Table it's required to 1. save the found items somewhere that survives between requests, or to 2. make a query that actually returns exactly what I accomplished with regular OOP PHP.
1. I think this could be accomplished by storing as a transitional value somewhere in the DB, and load that instead of the current way I've done. Also, it would need to flatten out the objects, and would make sense then to remove the unecessary data. Also, would need to change how I'm redirecting to the proper selected report, and how to display both pages. In the end, the work needed would extrapolate by a power factor over the 2 hours I've quickly spent doing this. And then, if the user wants to print, it would be needed remove pagination anyways.
2. This is just beyond my SQL knowledge, I tried to tackle the problem from this perspective, but that's impossible for me.

Maybe should leave as a future issue for implementing the pagination, as if a store with 10k-100k orders with 500+ events, this could actually be an issue.

**Comment by Shirkit** [comment]
Ok, that should do it.

Just wanted to clarify that the pagination was never implemented. To properly use Pagination while using a WP_List_Table it's required to 1. save the found items somewhere that survives between requests, or to 2. make a query that actually returns exactly what I accomplished with regular OOP PHP.
1. I think this could be accomplished by storing as a transitional value somewhere in the DB, and load that instead of the current way I've done. Also, it would need to flatten out the objects, and would make sense then to remove the unecessary data. Also, would need to change how I'm redirecting to the proper selected report, and how to display both pages. In the end, the work needed would extrapolate by a power factor over the 2 hours I've quickly spent doing this. And then, if the user wants to print, it would be needed remove pagination anyways.
2. This is just beyond my SQL knowledge, I tried to tackle the problem from this perspective, but that's impossible for me.

Maybe should leave as a future issue for implementing the pagination, as if a store with 10k-100k orders with 500+ events, this could actually be an issue.

**Pull request merged**
